export const INGREDIENTS = [
  "Vodka",
  "Gin",
  "Silver Rum",
  "Spiced Rum",
  "Tequila",
  "Bourbon",
  "Rye Whiskey",
  "Lemon Juice",
  "Lime Juice",
  "Simple Syrup",
  "Bitters",
  "Orange Bitters",
  "Campari",
  "Orange Juice",
].map((item) => item.toLowerCase());
